//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated using CodeSmith: v7.0.1, CSLA Templates: v4.0.0.0, CSLA Framework: v4.3.x.
//     Changes to this file will be lost after each regeneration.
//     To extend the functionality of this class, please modify the partial class 'BaseVouchPhoneInfo.cs'.
//
//     Template: ReadOnlyRoot.DataAccess.ParameterizedSQL.cst
//     Template website: http://code.google.com/p/codesmith/
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using MySql.Data.MySqlClient;

using Csla;
using Csla.Data;

namespace vjf.SyncTool.Business
{
    public partial class BaseVouchPhoneInfo
    {
        private void DataPortal_Fetch(BaseVouchPhoneCriteria criteria)
        {
            bool cancel = false;
            OnFetching(criteria, ref cancel);
            if (cancel) return;

            string commandText = String.Format("SELECT id, vid, guid, fid, phone, cost, type, created, status, isover, retmsg, begindate, expdate, usedate, city, product, store, paytype, usecanal, paycost, source, orderid, brandid FROM base_vouch_phone {0}", ADOHelper.BuildWhereStatement(criteria.StateBag));
            using (var connection = new MySqlConnection(ADOHelper.ConnectionString))
            {
                connection.Open();
                using (var command = new MySqlCommand(commandText, connection))
                {
                    command.Parameters.AddRange(ADOHelper.SqlParameters(criteria.StateBag));
                    using(var reader = new SafeDataReader(command.ExecuteReader()))
                    {
                        if (reader.Read())
                            Map(reader);
                        else
                            throw new System.Exception(String.Format("The record was not found in '.base_vouch_phone' using the following criteria: {0}.", criteria));
                    }
                }
            }

            OnFetched();
        }

        #region Map

        private void Map(SafeDataReader reader)
        {
            bool cancel = false;
            OnMapping(reader, ref cancel);
            if (cancel) return;

            LoadProperty(_identificationProperty, reader["id"]);
            LoadProperty(_vidProperty, reader["vid"]);
            LoadProperty(_guidProperty, reader["guid"]);
            LoadProperty(_fidProperty, reader["fid"]);
            LoadProperty(_phoneProperty, reader["phone"]);
            LoadProperty(_costProperty, reader["cost"]);
            LoadProperty(_typeProperty, reader["type"]);
            LoadProperty(_createdProperty, reader["created"]);
            LoadProperty(_statusProperty, reader["status"]);
            LoadProperty(_isoverProperty, reader["isover"]);
            LoadProperty(_retmsgProperty, reader["retmsg"]);
            LoadProperty(_begindateProperty, reader["begindate"]);
            LoadProperty(_expdateProperty, reader["expdate"]);
            LoadProperty(_usedateProperty, reader["usedate"]);
            LoadProperty(_cityProperty, reader["city"]);
            LoadProperty(_productProperty, reader["product"]);
            LoadProperty(_storeProperty, reader["store"]);
            LoadProperty(_paytypeProperty, reader["paytype"]);
            LoadProperty(_usecanalProperty, reader["usecanal"]);
            LoadProperty(_paycostProperty, reader["paycost"]);
            LoadProperty(_sourceProperty, reader["source"]);
            LoadProperty(_orderidProperty, reader["orderid"]);
            LoadProperty(_brandidProperty, reader["brandid"]);

            OnMapped();
        }

        private void Child_Fetch(SafeDataReader reader)
        {
            Map(reader);
        }

        #endregion
    }
}
