//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated using CodeSmith: v7.0.1, CSLA Templates: v4.0.0.0, CSLA Framework: v4.3.x.
//     Changes to this file will be lost after each regeneration.
//     To extend the functionality of this class, please modify the partial class 'BaseVouchActiveInfo.cs'.
//
//     Template: ReadOnlyRoot.DataAccess.ParameterizedSQL.cst
//     Template website: http://code.google.com/p/codesmith/
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using MySql.Data.MySqlClient;

using Csla;
using Csla.Data;

namespace vjf.SyncTool.Business
{
    public partial class BaseVouchActiveInfo
    {
        private void DataPortal_Fetch(BaseVouchActiveCriteria criteria)
        {
            bool cancel = false;
            OnFetching(criteria, ref cancel);
            if (cancel) return;

            string commandText = String.Format("SELECT id, title, begindate, enddate, vouchid, vouchnum, usernum, lnum, status, created, updated FROM base_vouch_active {0}", ADOHelper.BuildWhereStatement(criteria.StateBag));
            using (var connection = new MySqlConnection(ADOHelper.ConnectionString))
            {
                connection.Open();
                using (var command = new MySqlCommand(commandText, connection))
                {
                    command.Parameters.AddRange(ADOHelper.SqlParameters(criteria.StateBag));
                    using(var reader = new SafeDataReader(command.ExecuteReader()))
                    {
                        if (reader.Read())
                            Map(reader);
                        else
                            throw new System.Exception(String.Format("The record was not found in 'base_vouch_active' using the following criteria: {0}.", criteria));
                    }
                }
            }

            OnFetched();
        }

        #region Map

        private void Map(SafeDataReader reader)
        {
            bool cancel = false;
            OnMapping(reader, ref cancel);
            if (cancel) return;

            LoadProperty(_identificationProperty, reader["id"]);
            LoadProperty(_titleProperty, reader["title"]);
            LoadProperty(_begindateProperty, reader["begindate"]);
            LoadProperty(_enddateProperty, reader["enddate"]);
            LoadProperty(_vouchidProperty, reader["vouchid"]);
            LoadProperty(_vouchnumProperty, reader["vouchnum"]);
            LoadProperty(_usernumProperty, reader["usernum"]);
            LoadProperty(_lnumProperty, reader["lnum"]);
            LoadProperty(_statusProperty, reader["status"]);
            LoadProperty(_createdProperty, reader["created"]);
            LoadProperty(_updatedProperty, reader["updated"]);

            OnMapped();
        }

        private void Child_Fetch(SafeDataReader reader)
        {
            Map(reader);
        }

        #endregion
    }
}
