//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated using CodeSmith: v7.0.1, CSLA Templates: v4.0.0.0, CSLA Framework: v4.3.x.
//       Changes to this template will not be lost.
//
//     Template: ReadOnlyList.cst
//     Template website: http://code.google.com/p/codesmith/
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Csla;

namespace vjf.SyncTool.Business
{
    /// <summary>
    /// The BaseVouchPhoneInfoList class is a CSLA read only child root class collection of <see cref="BaseVouchPhoneInfo"/> objects.  See CSLA documentation for a more detailed description.
    /// </summary>
    /// <returns></returns>
    public partial class BaseVouchPhoneInfoList
    {
        #region Authorization Rules

        /// <summary>
        /// Allows the specification of CSLA based authorization rules for a collection list.  Specifies what roles can 
        /// perform which operations for a given business object
        /// </summary>
        protected void AddAuthorizationRules()
        {
            //Csla.Rules.BusinessRules.AddRule(typeof(BaseVouchPhoneInfoList), new Csla.Rules.CommonRules.IsInRole(Csla.Rules.AuthorizationActions.CreateObject, "SomeRole"));
            //Csla.Rules.BusinessRules.AddRule(typeof(BaseVouchPhoneInfoList), new Csla.Rules.CommonRules.IsInRole(Csla.Rules.AuthorizationActions.EditObject, "SomeRole"));
            //Csla.Rules.BusinessRules.AddRule(typeof(BaseVouchPhoneInfoList), new Csla.Rules.CommonRules.IsInRole(Csla.Rules.AuthorizationActions.DeleteObject, "SomeRole", "SomeAdminRole"));
        }
        #endregion
    }
}