//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated using CodeSmith: v7.0.1, CSLA Templates: v4.0.0.0, CSLA Framework: v4.3.x.
//     Changes to this file will be lost after each regeneration.
//     To extend the functionality of this class, please modify the partial class 'BaseVouchActiveInfoList.cs'.
//
//     Template: ReadOnlyList.Generated.cst
//     Template website: http://code.google.com/p/codesmith/
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;

using Csla;
using Csla.Data;

namespace vjf.SyncTool.Business
{
    [Serializable]
    public partial class BaseVouchActiveInfoList : ReadOnlyListBase<BaseVouchActiveInfoList, BaseVouchActiveInfo>
    {
        #region Contructor(s)

        public BaseVouchActiveInfoList()
        { /* Require use of factory methods */ }

        #endregion
    
        #region Synchronous Factory Methods

        /// <summary>
        /// Returns a <see cref="BaseVouchActiveInfoList"/> object of the specified criteria. 
        /// </summary>
        /// <param name="identification">No additional detail available.</param>
        /// <returns>A <see cref="BaseVouchActiveInfoList"/> object of the specified criteria.</returns>

        public static BaseVouchActiveInfoList GetByIdentification(System.String identification)
        {
            var criteria = new BaseVouchActiveCriteria{Identification = identification};
            
            
            return DataPortal.Fetch<BaseVouchActiveInfoList>(criteria);
        }
        

        public static BaseVouchActiveInfoList GetByCriteria(BaseVouchActiveCriteria criteria)
        {
            return DataPortal.Fetch<BaseVouchActiveInfoList>(criteria);
        }

        public static BaseVouchActiveInfoList GetAll()
        {
            return DataPortal.Fetch<BaseVouchActiveInfoList>(new BaseVouchActiveCriteria());
        }

        #endregion

        #region Asynchronous Factory Methods

        public static void GetByIdentificationAsync(System.String identification, EventHandler<DataPortalResult<BaseVouchActiveInfoList>> handler)
        {
            var criteria = new BaseVouchActiveCriteria{Identification = identification};
            
            
            var dp = new DataPortal<BaseVouchActiveInfoList>();
            dp.FetchCompleted += handler;
            dp.BeginFetch(criteria);
        }

        public static void GetByCriteriaAsync(BaseVouchActiveCriteria criteria, EventHandler<DataPortalResult<BaseVouchActiveInfoList>> handler)
        {  
            var dp = new DataPortal<BaseVouchActiveInfoList>();
            dp.FetchCompleted += handler;
            dp.BeginFetch(criteria);
        }

        public static void GetAllAsync(EventHandler<DataPortalResult<BaseVouchActiveInfoList>> handler)
        {
            var dp = new DataPortal<BaseVouchActiveInfoList>();
            dp.FetchCompleted += handler;
            dp.BeginFetch(new BaseVouchActiveCriteria());
        }

        #endregion

        #region DataPortal partial methods

        /// <summary>
        /// CodeSmith generated stub method that is called when creating the child <see cref="BaseVouchActiveInfo"/> object. 
        /// </summary>
        /// <param name="cancel">Value returned from the method indicating whether the object creation should proceed.</param>
        partial void OnCreating(ref bool cancel);

        /// <summary>
        /// CodeSmith generated stub method that is called after the child <see cref="BaseVouchActiveInfo"/> object has been created. 
        /// </summary>
        partial void OnCreated();

        /// <summary>
        /// CodeSmith generated stub method that is called when fetching the child <see cref="BaseVouchActiveInfo"/> object. 
        /// </summary>
        /// <param name="criteria"><see cref="BaseVouchActiveInfoCriteria"/> object containing the criteria of the object to fetch.</param>
        /// <param name="cancel">Value returned from the method indicating whether the object fetching should proceed.</param>
        partial void OnFetching(BaseVouchActiveCriteria criteria, ref bool cancel);

        /// <summary>
        /// CodeSmith generated stub method that is called after the child <see cref="BaseVouchActiveInfo"/> object has been fetched. 
        /// </summary>
        partial void OnFetched();

        /// <summary>
        /// CodeSmith generated stub method that is called when mapping the child <see cref="BaseVouchActiveInfo"/> object. 
        /// </summary>
        /// <param name="cancel">Value returned from the method indicating whether the object mapping should proceed.</param>
        partial void OnMapping(ref bool cancel);

        /// <summary>
        /// CodeSmith generated stub method that is called when mapping the child <see cref="BaseVouchActiveInfo"/> object. 
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="cancel">Value returned from the method indicating whether the object mapping should proceed.</param>
        partial void OnMapping(SafeDataReader reader, ref bool cancel);

        /// <summary>
        /// CodeSmith generated stub method that is called after the child <see cref="BaseVouchActiveInfo"/> object has been mapped. 
        /// </summary>
        partial void OnMapped();

        /// <summary>
        /// CodeSmith generated stub method that is called when updating the <see cref="BaseVouchActiveInfo"/> object. 
        /// </summary>
        /// <param name="cancel">Value returned from the method indicating whether the object creation should proceed.</param>
        partial void OnUpdating(ref bool cancel);

        /// <summary>
        /// CodeSmith generated stub method that is called after the <see cref="BaseVouchActiveInfo"/> object has been updated. 
        /// </summary>
        partial void OnUpdated();
        partial void OnAddNewCore(ref BaseVouchActiveInfo item, ref bool cancel);

        #endregion

        #region Exists Command

        /// <summary>
        /// Determines if a record exists in the BaseVouchActiveInfo in the database for the specified criteria. 
        /// </summary>
        /// <param name="criteria">The criteria parameter is a <see cref="BaseVouchActiveInfoList"/> object.</param>
        /// <returns>A boolean value of true is returned if a record is found.</returns>
        public static bool Exists(BaseVouchActiveCriteria criteria)
        {
            return vjf.SyncTool.Business.BaseVouchActiveInfo.Exists(criteria);
        }
        /// <summary>
        /// Determines if a record exists in the BaseVouchActiveInfo in the database for the specified criteria. 
        /// </summary>
        public static void ExistsAsync(BaseVouchActiveCriteria criteria, EventHandler<DataPortalResult<ExistsCommand>> handler)
        {
            vjf.SyncTool.Business.BaseVouchActiveInfo.ExistsAsync(criteria,handler);
        }

        #endregion
 
        #region Enhancements

        public BaseVouchActiveInfo GetBaseVouchActiveInfo(System.String identification)
        {
            return this.FirstOrDefault(i => i.Identification == identification);
        }

        public bool Contains(System.String identification)
        {
            return this.Count(i => i.Identification == identification) > 0;
        }

        #endregion
    }
}