//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated using CodeSmith: v7.0.1, CSLA Templates: v4.0.0.0, CSLA Framework: v4.3.x.
//       Changes to this template will not be lost.
//
//     Template: Criteria.cst
//     Template website: http://code.google.com/p/codesmith/
// </autogenerated>
//------------------------------------------------------------------------------
using System;

namespace vjf.SyncTool.Business
{
    public partial class BaseCouponCodeCriteria
    {
    }
}