//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated using CodeSmith: v7.0.1, CSLA Templates: v4.0.0.0, CSLA Framework: v4.3.x.
//     Changes to this file will be lost after each regeneration.
//     To extend the functionality of this class, please modify the partial class 'BaseVouchGroupUser.cs'.
//
//     Template: Criteria.Generated.cst
//     Template website: http://code.google.com/p/codesmith/
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using MySql.Data.MySqlClient;

using Csla;

namespace vjf.SyncTool.Business
{
    [Serializable]
    public partial class BaseVouchGroupUserCriteria : CriteriaBase<BaseVouchGroupUserCriteria>, IGeneratedCriteria
    {
        private readonly Dictionary<string, object> _bag = new Dictionary<string, object>();
        
        #region Constructors

        public BaseVouchGroupUserCriteria(){}

        public BaseVouchGroupUserCriteria(System.String identification)
        {
            this.Identification = identification;
        }

        #endregion

        #region Public Properties

        #region Read-Write

        public System.String Identification
        {
            get { return GetValue<System.String>("id"); }
            set { _bag["id"] = value; }
        }

        public System.String Fid
        {
            get { return GetValue<System.String>("fid"); }
            set { _bag["fid"] = value; }
        }

        public System.String VouchGid
        {
            get { return GetValue<System.String>("vouch_gid"); }
            set { _bag["vouch_gid"] = value; }
        }

        public System.String OrderId
        {
            get { return GetValue<System.String>("order_id"); }
            set { _bag["order_id"] = value; }
        }

        public System.Int32? VouchNum
        {
            get { return GetValue<System.Int32?>("vouch_num"); }
            set { _bag["vouch_num"] = value; }
        }

        public System.Int32? Lnum
        {
            get { return GetValue<System.Int32?>("lnum"); }
            set { _bag["lnum"] = value; }
        }

        public System.Int32? Created
        {
            get { return GetValue<System.Int32?>("created"); }
            set { _bag["created"] = value; }
        }

        public System.Int32? Updated
        {
            get { return GetValue<System.Int32?>("updated"); }
            set { _bag["updated"] = value; }
        }

        #endregion
        
        #region Read-Only

        /// <summary>
        /// Returns a list of all the modified properties and values.
        /// </summary>
        public Dictionary<string, object> StateBag
        {
            get
            {
                return _bag;
            }
        }

        /// <summary>
        /// Returns a list of all the modified properties and values.
        /// </summary>
        public string TableFullName
        {
            get
            {
                return "].base_vouch_group_user]";
            }
        }

        #endregion

        #endregion

        #region Overrides
        
        public override string ToString()
        {
            var result = String.Empty;
            var cancel = false;
            
            OnToString(ref result, ref cancel);
            if(cancel && !String.IsNullOrEmpty(result))
                return result;
            
            if (_bag.Count == 0)
                return "No criterion was specified.";

            foreach (KeyValuePair<string, object> key in _bag)
            {
                result += String.Format("{0} = '{1}' AND ", key.Key, key.Value);
            }

            return result.Remove(result.Length - 5, 5);
        }

        #endregion

        #region Private Methods
        private T GetValue<T>(string name)
        {
            object value;
            if (_bag.TryGetValue(name, out value))
                return (T) value;
        
            return default(T);
        }
        
        #endregion
        
        #region Partial Methods
        
        partial void OnToString(ref string result, ref bool cancel);
        
        #endregion
        
    }
}