//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated using CodeSmith: v7.0.1, CSLA Templates: v4.0.0.0, CSLA Framework: v4.3.x.
//     Changes to this file will be lost after each regeneration.
//     To extend the functionality of this class, please modify the partial class 'BaseRecharge.cs'.
//
//     Template: Criteria.Generated.cst
//     Template website: http://code.google.com/p/codesmith/
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using MySql.Data.MySqlClient;

using Csla;

namespace vjf.SyncTool.Business
{
    [Serializable]
    public partial class BaseRechargeCriteria : CriteriaBase<BaseRechargeCriteria>, IGeneratedCriteria
    {
        private readonly Dictionary<string, object> _bag = new Dictionary<string, object>();
        
        #region Constructors

        public BaseRechargeCriteria(){}

        public BaseRechargeCriteria(System.Int32 identification)
        {
            this.Identification = identification;
        }

        #endregion

        #region Public Properties

        #region Read-Write

        public System.Int32 Identification
        {
            get { return GetValue<System.Int32>("id"); }
            set { _bag["id"] = value; }
        }

        public System.String Orderid
        {
            get { return GetValue<System.String>("orderid"); }
            set { _bag["orderid"] = value; }
        }

        public System.String Phone
        {
            get { return GetValue<System.String>("phone"); }
            set { _bag["phone"] = value; }
        }

        public System.String Carno
        {
            get { return GetValue<System.String>("carno"); }
            set { _bag["carno"] = value; }
        }

        public System.String Province
        {
            get { return GetValue<System.String>("province"); }
            set { _bag["province"] = value; }
        }

        public System.String City
        {
            get { return GetValue<System.String>("city"); }
            set { _bag["city"] = value; }
        }

        public System.String Pid
        {
            get { return GetValue<System.String>("pid"); }
            set { _bag["pid"] = value; }
        }

        public System.Int32? Pnum
        {
            get { return GetValue<System.Int32?>("pnum"); }
            set { _bag["pnum"] = value; }
        }

        public System.Single? Amount
        {
            get { return GetValue<System.Single?>("amount"); }
            set { _bag["amount"] = value; }
        }

        public System.Single? Fee
        {
            get { return GetValue<System.Single?>("fee"); }
            set { _bag["fee"] = value; }
        }

        public System.Int16 Status
        {
            get { return GetValue<System.Int16>("status"); }
            set { _bag["status"] = value; }
        }

        public System.Int16? Paytype
        {
            get { return GetValue<System.Int16?>("paytype"); }
            set { _bag["paytype"] = value; }
        }

        public System.String Serialnum
        {
            get { return GetValue<System.String>("serialnum"); }
            set { _bag["serialnum"] = value; }
        }

        public System.Int32? Activetime
        {
            get { return GetValue<System.Int32?>("activetime"); }
            set { _bag["activetime"] = value; }
        }

        public System.Int16 Expdate
        {
            get { return GetValue<System.Int16>("expdate"); }
            set { _bag["expdate"] = value; }
        }

        public System.String Cardno
        {
            get { return GetValue<System.String>("cardno"); }
            set { _bag["cardno"] = value; }
        }

        public System.String Protype
        {
            get { return GetValue<System.String>("protype"); }
            set { _bag["protype"] = value; }
        }

        public System.String Remark
        {
            get { return GetValue<System.String>("remark"); }
            set { _bag["remark"] = value; }
        }

        public System.Int32? Created
        {
            get { return GetValue<System.Int32?>("created"); }
            set { _bag["created"] = value; }
        }

        public System.String Createid
        {
            get { return GetValue<System.String>("createid"); }
            set { _bag["createid"] = value; }
        }

        public System.Int16 Ispay
        {
            get { return GetValue<System.Int16>("ispay"); }
            set { _bag["ispay"] = value; }
        }

        public System.Int32 Paytime
        {
            get { return GetValue<System.Int32>("paytime"); }
            set { _bag["paytime"] = value; }
        }

        public System.String Area
        {
            get { return GetValue<System.String>("area"); }
            set { _bag["area"] = value; }
        }

        #endregion
        
        #region Read-Only

        /// <summary>
        /// Returns a list of all the modified properties and values.
        /// </summary>
        public Dictionary<string, object> StateBag
        {
            get
            {
                return _bag;
            }
        }

        /// <summary>
        /// Returns a list of all the modified properties and values.
        /// </summary>
        public string TableFullName
        {
            get
            {
                return "[].[base_recharge]";
            }
        }

        #endregion

        #endregion

        #region Overrides
        
        public override string ToString()
        {
            var result = String.Empty;
            var cancel = false;
            
            OnToString(ref result, ref cancel);
            if(cancel && !String.IsNullOrEmpty(result))
                return result;
            
            if (_bag.Count == 0)
                return "No criterion was specified.";

            foreach (KeyValuePair<string, object> key in _bag)
            {
                result += String.Format("{0} = '{1}' AND ", key.Key, key.Value);
            }

            return result.Remove(result.Length - 5, 5);
        }

        #endregion

        #region Private Methods
        private T GetValue<T>(string name)
        {
            object value;
            if (_bag.TryGetValue(name, out value))
                return (T) value;
        
            return default(T);
        }
        
        #endregion
        
        #region Partial Methods
        
        partial void OnToString(ref string result, ref bool cancel);
        
        #endregion
        
    }
}