//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated using CodeSmith: v7.0.1, CSLA Templates: v4.0.0.0, CSLA Framework: v4.3.x.
//     Changes to this file will be lost after each regeneration.
//     To extend the functionality of this class, please modify the partial class 'BaseVouchGroup.cs'.
//
//     Template: Criteria.Generated.cst
//     Template website: http://code.google.com/p/codesmith/
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using MySql.Data.MySqlClient;

using Csla;

namespace vjf.SyncTool.Business
{
    [Serializable]
    public partial class BaseVouchGroupCriteria : CriteriaBase<BaseVouchGroupCriteria>, IGeneratedCriteria
    {
        private readonly Dictionary<string, object> _bag = new Dictionary<string, object>();
        
        #region Constructors

        public BaseVouchGroupCriteria(){}

        public BaseVouchGroupCriteria(System.String identification)
        {
            this.Identification = identification;
        }

        #endregion

        #region Public Properties

        #region Read-Write

        public System.String Identification
        {
            get { return GetValue<System.String>("id"); }
            set { _bag["id"] = value; }
        }

        public System.String Title
        {
            get { return GetValue<System.String>("title"); }
            set { _bag["title"] = value; }
        }

        public System.String City
        {
            get { return GetValue<System.String>("city"); }
            set { _bag["city"] = value; }
        }

        public System.Int32? BeginDate
        {
            get { return GetValue<System.Int32?>("begin_date"); }
            set { _bag["begin_date"] = value; }
        }

        public System.Int32? EndDate
        {
            get { return GetValue<System.Int32?>("end_date"); }
            set { _bag["end_date"] = value; }
        }

        public System.String NodeProduct
        {
            get { return GetValue<System.String>("node_product"); }
            set { _bag["node_product"] = value; }
        }

        public System.String Product
        {
            get { return GetValue<System.String>("product"); }
            set { _bag["product"] = value; }
        }

        public System.String VouchNum
        {
            get { return GetValue<System.String>("vouch_num"); }
            set { _bag["vouch_num"] = value; }
        }

        public System.Int32 Expday
        {
            get { return GetValue<System.Int32>("expday"); }
            set { _bag["expday"] = value; }
        }

        public System.String NewUserCost
        {
            get { return GetValue<System.String>("new_user_cost"); }
            set { _bag["new_user_cost"] = value; }
        }

        public System.String NewUser
        {
            get { return GetValue<System.String>("new_user"); }
            set { _bag["new_user"] = value; }
        }

        public System.String OldUserCost
        {
            get { return GetValue<System.String>("old_user_cost"); }
            set { _bag["old_user_cost"] = value; }
        }

        public System.String OldUser
        {
            get { return GetValue<System.String>("old_user"); }
            set { _bag["old_user"] = value; }
        }

        public System.Int32? PerVouchNum
        {
            get { return GetValue<System.Int32?>("per_vouch_num"); }
            set { _bag["per_vouch_num"] = value; }
        }

        public System.Int16? Status
        {
            get { return GetValue<System.Int16?>("status"); }
            set { _bag["status"] = value; }
        }

        public System.Int32? Created
        {
            get { return GetValue<System.Int32?>("created"); }
            set { _bag["created"] = value; }
        }

        public System.String CreatedUid
        {
            get { return GetValue<System.String>("created_uid"); }
            set { _bag["created_uid"] = value; }
        }

        public System.Int32? Updated
        {
            get { return GetValue<System.Int32?>("updated"); }
            set { _bag["updated"] = value; }
        }

        public System.String UpdatedUid
        {
            get { return GetValue<System.String>("updated_uid"); }
            set { _bag["updated_uid"] = value; }
        }

        #endregion
        
        #region Read-Only

        /// <summary>
        /// Returns a list of all the modified properties and values.
        /// </summary>
        public Dictionary<string, object> StateBag
        {
            get
            {
                return _bag;
            }
        }

        /// <summary>
        /// Returns a list of all the modified properties and values.
        /// </summary>
        public string TableFullName
        {
            get
            {
                return "].base_vouch_group]";
            }
        }

        #endregion

        #endregion

        #region Overrides
        
        public override string ToString()
        {
            var result = String.Empty;
            var cancel = false;
            
            OnToString(ref result, ref cancel);
            if(cancel && !String.IsNullOrEmpty(result))
                return result;
            
            if (_bag.Count == 0)
                return "No criterion was specified.";

            foreach (KeyValuePair<string, object> key in _bag)
            {
                result += String.Format("{0} = '{1}' AND ", key.Key, key.Value);
            }

            return result.Remove(result.Length - 5, 5);
        }

        #endregion

        #region Private Methods
        private T GetValue<T>(string name)
        {
            object value;
            if (_bag.TryGetValue(name, out value))
                return (T) value;
        
            return default(T);
        }
        
        #endregion
        
        #region Partial Methods
        
        partial void OnToString(ref string result, ref bool cancel);
        
        #endregion
        
    }
}